### ISSUE TITLE
Colorama is not defined 

### ISSUE THREAD

**Issue by Thman558** [debaet/IXLMultiBot#1]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    colorama.init()
NameError: name 'colorama' is not defined

**Comment by debaet** [comment]
Hello, this is not an error with the code, this is an error with your machine as you do not have Colorama installed. 
so please open a command prompt and simply type pip install colorama.

**Comment by debaet** [comment]
Hello, please download the updated version of the code.
